import { redirect } from "next/navigation";
import { connection } from "next/server";
import { AppHeader } from "@/src/components/navigation/app-header";
import { getAuthorizedUser } from "@/src/lib/authz";
import { prisma } from "@/src/lib/db";
import { personnelDisplayName } from "@/src/lib/personnel-display";
import { getLikelyPersonnelDuplicates, getPersonnelReconciliation } from "@/src/lib/naeron/personnel-reconciliation";
import { linkNaeronPersonnelManually, runSafePersonnelReconciliation } from "@/app/admin/personnel-reconciliation/actions";

interface PageProps { searchParams: Promise<{ status?: string; message?: string }> }

export default async function PersonnelReconciliationPage({ searchParams }: PageProps) {
  await connection(); const [user, query] = await Promise.all([getAuthorizedUser(), searchParams]);
  if (!user) redirect("/login"); if (user.role !== "ADMIN") redirect("/");
  const [items, personnel, duplicates] = await Promise.all([
    getPersonnelReconciliation(),
    prisma.personnel.findMany({ orderBy: [{ firstName: "asc" }, { lastName: "asc" }], select: { id: true, firstName: true, lastName: true, canonicalFullName: true, team: { select: { name: true } } } }),
    getLikelyPersonnelDuplicates(),
  ]);
  const counts = { matched: items.filter((item) => item.status === "AUTO_MATCHED").length, review: items.filter((item) => item.status === "REVIEW_REQUIRED").length, unmatched: items.filter((item) => item.status === "UNMATCHED").length };
  return <main className="min-h-screen bg-slate-50 px-4 py-6 dark:bg-[#0b0f19] sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <AppHeader title="Personel Eşleştirme" subtitle="Naeron stable kimliklerini mevcut PDF personeliyle güvenli biçimde bağlayın" eyebrow="Admin · Data Quality" />
    {query.message ? <div role="status" className={`rounded-2xl border p-4 text-sm ${query.status === "error" ? "border-red-200 bg-red-50 text-red-700 dark:border-red-500/30 dark:bg-red-500/10 dark:text-red-300" : "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-300"}`}>{query.message}</div> : null}
    <section className="grid gap-3 sm:grid-cols-3">{[["Auto Matched",counts.matched,"text-emerald-600"],["Review Required",counts.review,"text-amber-600"],["Unmatched",counts.unmatched,"text-red-600"]].map(([label,value,color]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${color}`}>{value}</p></div>)}</section>
    <form action={runSafePersonnelReconciliation} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-500/30 dark:bg-blue-500/10"><p className="text-sm text-blue-800 dark:text-blue-200">Yalnızca stable ID, tekil tam isim veya PersonnelAlias eşleşmeleri uygulanır. Kayıt silinmez veya birleştirilmez.</p><button className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Güvenli Eşleşmeleri Uygula</button></form>
    <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 className="font-semibold">Naeron Eğitmenleri</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th className="px-4 py-3">Naeron Name</th><th className="px-4 py-3">Current Personnel</th><th className="px-4 py-3">Naeron i_ID</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{items.map((item) => <tr key={item.key}><td className="px-4 py-3 font-semibold">{item.name}<p className="text-xs font-normal text-slate-500">VM: {item.vmId ?? "-"}</p></td><td className="px-4 py-3">{item.personnelName ?? "—"}</td><td className="px-4 py-3 font-mono text-xs">{item.employeeId ?? "—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.status === "AUTO_MATCHED" ? "bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300" : item.status === "REVIEW_REQUIRED" ? "bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300" : "bg-red-100 text-red-700 dark:bg-red-500/15 dark:text-red-300"}`}>{item.status}</span><p className="mt-1 text-xs text-slate-500">{item.confidence}</p></td><td className="px-4 py-3"><form action={linkNaeronPersonnelManually} className="flex min-w-72 gap-2"><input type="hidden" name="identityKey" value={item.key}/><select name="personnelId" defaultValue={item.personnelId ?? ""} required className="min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-2 py-1.5 text-xs dark:border-slate-700 dark:bg-slate-800"><option value="">Personel seçin</option>{personnel.map((person) => <option key={person.id} value={person.id}>{personnelDisplayName(person)} · {person.team?.name ?? "Ekip yok"}</option>)}</select><button className="rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-semibold text-white dark:bg-slate-100 dark:text-slate-900">Bağla</button></form></td></tr>)}</tbody></table></div></section>
    <section className="rounded-[28px] border border-amber-200 bg-amber-50/50 p-5 dark:border-amber-500/30 dark:bg-amber-500/5"><h2 className="font-semibold text-amber-900 dark:text-amber-200">Muhtemel Yinelenen Personel</h2><p className="mt-1 text-sm text-amber-700 dark:text-amber-300">Otomatik merge yapılmaz. Bu liste yalnızca inceleme içindir.</p><div className="mt-4 space-y-2">{duplicates.map((pair) => <div key={`${pair.first.id}:${pair.second.id}`} className="rounded-xl bg-white p-3 text-sm dark:bg-slate-900"><b>{personnelDisplayName(pair.first)}</b> ↔ <b>{personnelDisplayName(pair.second)}</b><span className="ml-2 text-xs text-amber-700 dark:text-amber-300">{pair.reason}</span></div>)}{!duplicates.length ? <p className="text-sm text-slate-500">Güçlü duplicate adayı bulunmadı.</p> : null}</div></section>
  </div></main>;
}
