import { connection } from "next/server";
import { AppHeader } from "@/src/components/navigation/app-header";
import { AnalyticsNav, RangeFilter } from "@/src/components/analytics/analytics-nav";
import { requirePermission } from "@/src/lib/authz";
import { prisma } from "@/src/lib/db";
import { analyticsRange } from "@/src/lib/flights/range";
import { formatDuration } from "@/src/lib/flights/time";

interface PageProps { searchParams: Promise<Record<string,string|undefined>> }
export default async function AnalyticsPage({searchParams}:PageProps){await connection();await requirePermission("VIEW_DASHBOARD");const q=await searchParams;const {from,to}=analyticsRange(q);const metric=q.metric==="count"?"count":"duration";
  const flights=await prisma.flight.findMany({where:{flightDate:{gte:from,lte:to},archivedAt:null},select:{flightDate:true,sortieDurationMinutes:true,instructorId:true,studentId:true,aircraftId:true,instructor:{select:{firstName:true,lastName:true}},student:{select:{displayName:true}},aircraft:{select:{registration:true}}}});
  const days=new Map<string,{count:number,minutes:number}>();for(let d=new Date(from);d<=to;d.setUTCDate(d.getUTCDate()+1))days.set(d.toISOString().slice(0,10),{count:0,minutes:0});for(const f of flights){const key=f.flightDate.toISOString().slice(0,10);const day=days.get(key)??{count:0,minutes:0};day.count++;day.minutes+=f.sortieDurationMinutes??0;days.set(key,day)}
  const rank=<T extends string>(items:Array<{id:T|null;name:string;minutes:number}>)=>Array.from(items.reduce((map,x)=>{if(!x.id)return map;const v=map.get(x.id)??{name:x.name,count:0,minutes:0};v.count++;v.minutes+=x.minutes;map.set(x.id,v);return map},new Map<T,{name:string;count:number;minutes:number}>())).sort((a,b)=>metric==="count"?b[1].count-a[1].count:b[1].minutes-a[1].minutes).slice(0,5);
  const instructors=rank(flights.map(f=>({id:f.instructorId,name:f.instructor?`${f.instructor.firstName} ${f.instructor.lastName}`:"-",minutes:f.sortieDurationMinutes??0})));const students=rank(flights.map(f=>({id:f.studentId,name:f.student?.displayName??"-",minutes:f.sortieDurationMinutes??0})));const aircraft=rank(flights.map(f=>({id:f.aircraftId,name:f.aircraft.registration,minutes:f.sortieDurationMinutes??0})));
  const max=Math.max(1,...Array.from(days.values()).map(x=>metric==="count"?x.count:x.minutes));
  return <main className="min-h-screen bg-slate-50 px-4 py-6 dark:bg-[#0b0f19] sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6"><AppHeader title="Uçuş Analitiği" subtitle="Tamamlanan uçuş trendleri ve öne çıkanlar"/><AnalyticsNav/><RangeFilter preset={q.preset} from={q.from} to={q.to}/><div className="flex gap-2"><a href={`?preset=${q.preset??"7"}&metric=duration`} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white">Duration</a><a href={`?preset=${q.preset??"7"}&metric=count`} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold dark:border-slate-700">Sortie count</a></div>
    <section className="rounded-[28px] border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-semibold">Daily {metric==="count"?"sortie count":"total sortie duration"}</h2><div className="mt-6 flex h-56 items-end gap-1 overflow-x-auto">{Array.from(days).map(([date,value])=>{const n=metric==="count"?value.count:value.minutes;return <div key={date} className="flex min-w-8 flex-1 flex-col items-center gap-1" title={`${date}: ${metric==="count"?n:formatDuration(n)}`}><span className="text-[10px]">{metric==="count"?n:formatDuration(n)}</span><div className="w-full rounded-t bg-blue-500" style={{height:`${Math.max(2,n/max*160)}px`}}/><span className="text-[9px] text-slate-500">{date.slice(5)}</span></div>})}</div></section>
    <div className="grid gap-5 lg:grid-cols-3">{[["Most active instructors",instructors],["Most active students",students],["Most used aircraft",aircraft]].map(([title,data])=><section key={title as string} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">{title as string}</h2><ol className="mt-3 space-y-2">{(data as typeof instructors).map(([id,v],i)=><li key={id} className="flex justify-between rounded-xl bg-slate-50 p-2 dark:bg-slate-800"><span>{i+1}. {v.name}</span><b>{metric==="count"?v.count:formatDuration(v.minutes)}</b></li>)}</ol></section>)}</div>
  </div></main>}
